services:
  backend:
    build: ./backend_api
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./.env

  frontend:
    build: ./frontend_flutter
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./.env
