services:
  backend:
    build: ./backend_api
    ports:
      - "3000:3000"
    env_file:
      - .env

  frontend:
    build: ./frontend_flutter
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - .env
