name: herramienta_control_gastos
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Esto es más flexible y evita errores de versión

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  crypto: ^3.0.3
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.69.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 #La versión 6.0.0 no es la estándar estable todavía

flutter:
  uses-material-design: true
  assets:
    - .env